# permissions for end users to edit serviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argocd-mca
    app.kubernetes.io/part-of: argocd-mca
    app.kubernetes.io/managed-by: kustomize
  name: serviceaccount-editor-role
rules:
- apiGroups:
  - argocd.arthurvardevanyan.com
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.arthurvardevanyan.com
  resources:
  - serviceaccounts/status
  verbs:
  - get
