apiVersion: argocd.arthurvardevanyan.com/v1beta1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: serviceaccount-sample
    app.kubernetes.io/part-of: argocd-mca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: argocd-mca
  name: serviceaccount-sample
spec:
  # TODO(user): Add fields here
